### ISSUE TITLE
Workflow to publish on Pypi on a new version tag

### ISSUE THREAD

**Issue by anxuae** [Faylixe/pygame-vkeyboard#15]
I try this action script to auto-publish package on Pypi when a new git tag is pushed. Maybe you can setup something like that?

To make it running, you have to setup these 2 variables on in your settings/secrets:
`PYPI_USERNAME`
`PYPI_PASSWORD`

This is the script:

```
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py bdist_wheel
        twine upload dist/*
```
